
   
name: integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Install Dependencies
        run: yarn
      - name: Check Lint Rules
        run: yarn lint

  test:
    name: Build and Test
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-20.04, windows-2019]
    runs-on: ${{ matrix.os }}
    env:
      OS: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Install Dependencies
        run: yarn
      - name: Build Packages
        run: yarn build
      - name: Run Tests
        run: yarn test
